# doctest for 7-base_geometry.py

>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

>>> bg = BaseGeometry()
>>> bg.integer_validator("my_int", 1)

>>> bg.integer_validator("width", 1)

>>> bg.integer_validator("name", "Luis")
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg2 = BaseGeometry()

>>> bg2.integer_validator("my_int", 12)

>>> bg2.integer_validator("width", 89)

>>> bg2.integer_validator("", 12)

>>> bg2.area()
Traceback (most recent call last):
Exception: area() is not implemented

>>> bg2.integer_validator()
Traceback (most recent call last):
TypeError: integer_validator() takes exactly 3 arguments (1 given)

>>> bg2.integer_validator(50)
Traceback (most recent call last):
TypeError: integer_validator() takes exactly 3 arguments (2 given)

>>> bg2.integer_validator("", 12)

>>> bg2.integer_validator("name", "string")
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg2.integer_validator("name", None)
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg2.integer_validator("name", {3, 1})
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg2.integer_validator("name", ())
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg2.integer_validator("name", [])
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg2.integer_validator("name", True)
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg2.integer_validator("name", 3.5)
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg2.integer_validator("x", 0)
Traceback (most recent call last):
...
ValueError: x ust be greater than 0

>>> bg2.integer_validator("x", -4)
Traceback (most recent call last):
...
ValueError: x ust be greater than 0